### ISSUE TITLE
Rework briefing to HTML/restructure briefing tabs

### ISSUE THREAD

**Issue by CER10TY** [ARCOMM/ARCMF2#4]
Pushing this over from ARCMF1 for reasons.

https://github.com/ARCOMM/ARCMF/issues/85

**Comment by jameslkingsley** [comment]
ARCMF2 is using Eden attributes to handle the briefing. There's multiple sections that you can fill out and if we need more we can easily add more sections. This is best imo because it keeps a consistent format.
